"""Flat Moebius strip: the quotient idea again, now with a twist and a boundary.

The space
---------
Take the infinite flat strip R x [0, w] with coordinates (x, y), and identify
points under the GLIDE REFLECTION

    g(x, y) = (x + L, w - y).

Walking a distance L in x brings you back to the strip - but mirrored in y.
Defaults, pinned project-wide: L = 2 pi, w = 1. The result is flat (zero
curvature), non-orientable, and has a single boundary circle (the images of
y = 0 and y = w are glued into one). It is the only manifold in this set with
either property.

CRITICAL distinction - read twice. The paper-strip Moebius band you can make
with your hands (and the standard "ruled" picture in R^3 that `embed`
produces) is NOT this metric. The ruled surface is not flat, is not isometric
to the flat quotient, and has no closed-form distance. We compute distances in
the FLAT QUOTIENT model and use the R^3 picture ONLY for plotting. This is why
`ambient_metric_is_induced` is False: measured on random pairs, the "invariant"
d_geo >= d_amb fails against the ruled embedding on ~21% of pairs (by up to
~0.51). If you test that inequality here and it fails, your code is fine; the
test does not apply.

Distance (what you implement)
-----------------------------
Same universal-cover minimum as the flat torus, but the deck group is
generated by the glide reflection instead of two translations:

    d(p, q) = min over k in Z of || p - g^k(q) ||,
    g^k(q) = (q_x + k L, q_y)      for even k,
             (q_x + k L, w - q_y)  for odd  k.

|k| <= 3 is more than sufficient at L = 2 pi, w = 1 (measured: the window
|k| <= 3 and |k| <= 6 agree exactly on 100k random pairs).

Do you need to add images REFLECTED across y = 0 and y = w (paths that bounce
off the boundary)? No - and it is worth understanding why. The covering strip
is CONVEX, so the straight segment between p and any interior image g^k(q)
stays inside the strip; and a two-line computation shows the reflected image
is never closer: for y_p, y_q >= 0,

    ||p - q'||^2 - ||p - refl(q')||^2 = (y_p - y_q)^2 - (y_p + y_q)^2
                                      = -4 y_p y_q <= 0.

Measured: reflected images win on 0 of 100k random pairs. If your boundary
handling changes any distance, the bug is in your boundary handling.

The bug this manifold exists to teach (measured): forget the y-flip on odd k
- treat the strip as a cylinder. The resulting function is a perfectly valid
metric (it is the CYLINDER's metric), so it passes symmetry, identity, and
the triangle inequality on every random triple. The tests that catch it are
the identification tests:

    d(p, g(p)) == 0      (a point and its glide image are the SAME point;
                          the buggy version returns up to w)
    d(p, g(q)) == d(p, q)

Always test the quotient identification directly; metric axioms cannot see it.

Sampling
--------
Uniform on the fundamental domain [0, L) x [0, w]: exactly correct (flat,
constant area element).

Isometries for the invariance test: x-translations (x, y) -> (x + t, y); the
y-flip (x, y) -> (x, w - y); the reflection (x, y) -> (-x, y). And g itself
must act as the identity.

A geodesic that goes once around the strip returns with y flipped - plot one
with `embed` and see the half twist do it.
"""

from __future__ import annotations

import numpy as np

from .base import Manifold


class FlatMobiusStrip(Manifold):
    """Flat Moebius strip; chart points (x, y), x any real, y in [0, w].

    x lives on the covering line (any real is valid; x and x + 2 L name the
    same point, x and x + L the mirrored point). y is a HARD boundary:
    validation rejects y outside [0, w]. `sample` returns canonical
    representatives in [0, L) x [0, w].
    """

    name = "flat_mobius"
    intrinsic_dim = 2
    ambient_dim = 3
    point_shape = (2,)
    ambient_metric_is_induced = False  # ruled embedding is a picture, not a ruler

    def __init__(self, length: float = 2.0 * np.pi, width: float = 1.0):
        if not (length > 0 and width > 0):
            raise ValueError("length and width must be positive")
        self.length = float(length)
        self.width = float(width)

    def _validate_points(self, points: np.ndarray) -> None:
        if not np.isfinite(points).all():
            i = int(np.argmax(~np.isfinite(points).all(axis=1)))
            raise ValueError(
                f"flat_mobius: non-finite chart point at row {i}: {points[i]}")
        y = points[:, 1]
        bad = (y < 0) | (y > self.width)
        if bad.any():
            i = int(np.argmax(bad))
            raise ValueError(
                f"flat_mobius: y = {y[i]:.6g} outside [0, {self.width}] at "
                f"row {i}; the strip has a real boundary, points beyond it do "
                f"not exist")

    def _sample(self, n: int, rng: np.random.Generator) -> np.ndarray:
        """Uniform on [0, L) x [0, w] - exactly Riemannian-uniform (flat)."""
        raise NotImplementedError

    def _distance(self, p: np.ndarray, q: np.ndarray) -> np.ndarray:
        """Min over glide images g^k(q), k in [-3, 3]; mind the odd-k y-flip.

        Vectorizable across the batch with a small loop over k. Before you
        ship it: run the quotient tests d(p, g(p)) = 0 and
        d(p, g(q)) = d(p, q) - they are the only tests that catch the
        forgot-the-flip bug (see module docstring).
        """
        raise NotImplementedError

    def _embed(self, points: np.ndarray) -> np.ndarray:
        """Standard ruled Moebius band in R^3. PLOTTING ONLY - not isometric.

        With phi = 2 pi x / L and rho = y - w/2 (signed offset from the center
        line, which turns by phi/2 - the half twist):

            ( (a + rho cos(phi/2)) cos phi,
              (a + rho cos(phi/2)) sin phi,
               rho sin(phi/2) ),         center-circle radius a = 1.

        Check your formula respects the identification: embed(g(p)) must equal
        embed(p) exactly, else your plots will show a seam.
        """
        raise NotImplementedError
